install.packages("elevatr")
require(elevatr)
library(osmdata)
library(raster)
library(sf)
mendoza <- getbb(place_name = "Mendoza, Argentina",format_out = "sf_polygon")
elevation_data <-get_elev_raster(mendoza,z = 9, src = "aws")
map <- raster::extract(elevation_data, mendoza)
plot(elevation_data, axes=TRUE)
plot(st_geometry(mendoza), add=TRUE)
